export const projects = [
  {
    title: 'Yoica.com',
    desc: 'Plataforma de productos naturales enfocada en bienestar con diseno limpio y conversion optimizada.',
    category: 'E-commerce',
    tags: ['WordPress', 'WooCommerce', 'SEO'],
    link: 'https://yoica.com',
    image: '/images/yoica.png',
    gradient: 'from-emerald-500 to-teal-500',
  },
  {
    title: 'SembrandoConfianza.com',
    desc: 'Agricultura sostenible con enfoque comunitario. Migracion completa y optimizacion SEO local.',
    category: 'Desarrollo Web',
    tags: ['WordPress', 'SEO', 'Migracion'],
    link: 'https://sembrandoconfianza.com/',
    image: '/images/sembrando.png',
    gradient: 'from-green-500 to-lime-500',
  },
  {
    title: 'ConoceTusDerechos.co',
    desc: 'Plataforma informativa para asesoria juridica con foco en accesibilidad y experiencia de usuario.',
    category: 'Informativo',
    tags: ['UX/UI', 'Accesibilidad', 'WordPress'],
    link: 'https://conocetusderechos.co/',
    image: '/images/conoce.png',
    gradient: 'from-blue-500 to-indigo-500',
  },
  {
    title: 'TiendaDelChocolate.com',
    desc: 'E-commerce premium para chocolates artesanales con integracion WooCommerce y diseno de marca.',
    category: 'E-commerce',
    tags: ['WooCommerce', 'Branding', 'Premium'],
    link: 'https://tiendadelchocolate.com/',
    image: '/images/chocolate.png',
    gradient: 'from-amber-600 to-orange-600',
  },
  {
    title: 'Ananassa.co',
    desc: 'E-commerce de fresas con chocolate. SEO GEO, analitica, UX moderno y automatizacion.',
    category: 'E-commerce',
    tags: ['E-commerce', 'SEO GEO', 'IA'],
    link: 'https://ananassa.co/',
    image: '/images/ananassa.png',
    gradient: 'from-pink-500 to-rose-500',
  },
  {
    title: 'WooCar.io',
    desc: 'Aplicacion web para alquiler de vehiculos electricos, conectada a API y backend personalizado.',
    category: 'App Web',
    tags: ['React', 'API', 'Backend'],
    link: 'https://woocar.io/',
    image: '/images/woocar.png',
    gradient: 'from-cyan-500 to-blue-500',
  },
  {
    title: 'Florida2R.com',
    desc: 'Sitio inmobiliario con filtros avanzados y fichas dinamicas integradas con CRM.',
    category: 'Inmobiliario',
    tags: ['CRM', 'Filtros', 'WordPress'],
    link: 'http://florida2r.com/',
    image: '/images/florida.png',
    gradient: 'from-violet-500 to-purple-500',
  },
  {
    title: 'Cristian.click',
    desc: 'Portfolio personal optimizado con animaciones React y estructura escalable para SEO tecnico.',
    category: 'Portfolio',
    tags: ['React', 'SEO', 'Animaciones'],
    link: 'https://cristian.click',
    image: '/images/portafolio.png',
    gradient: 'from-slate-500 to-gray-600',
  },
  {
    title: 'KLDiseoYConstruccion.com',
    desc: 'Sitio corporativo de arquitectura con enfoque en estetica, velocidad y SEO.',
    category: 'Corporativo',
    tags: ['Corporativo', 'SEO', 'Diseno'],
    link: 'https://kldisenoyconstruccion.com/',
    image: '/images/kldiseno.png',
    gradient: 'from-orange-500 to-red-500',
  },
  {
    title: 'BicicletasElectricasBogota.com.co',
    desc: 'Tienda de movilidad electrica con UX enfocado en conversiones y productos dinamicos.',
    category: 'E-commerce',
    tags: ['E-commerce', 'SEO GEO', 'Conversion'],
    link: 'https://bicicletaselectricasbogota.com.co/',
    image: '/images/bicicletas.png',
    gradient: 'from-green-500 to-emerald-500',
  },
  {
    title: 'ImperialDunas.com',
    desc: 'Resort de lujo frente al mar con diseno premium, integracion de reservas y optimizacion global.',
    category: 'Hospitality',
    tags: ['Premium', 'Reservas', 'Performance'],
    link: 'https://imperialdunas.com/',
    image: '/images/imperial.png',
    gradient: 'from-blue-600 to-cyan-600',
  },
  {
    title: 'Hoffman-Latam.com',
    desc: 'Mantenimiento tecnico y optimizacion de rendimiento para empresa de fotografia profesional.',
    category: 'Mantenimiento',
    tags: ['Mantenimiento', 'Performance', 'Fotografia'],
    link: 'https://hoffman-latam.com/',
    image: '/images/hoffman.png',
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    title: 'Chatbot WhatsApp con IA',
    desc: 'Bot de WhatsApp con IA para automatizar atencion y ventas sobre WhatsApp Business API.',
    category: 'Automatizacion',
    tags: ['WhatsApp API', 'IA', 'Automatizacion'],
    link: 'https://github.com/Crnustes/api_whatsapp_techtecnic',
    image: '/images/chatbot-whatsapp-business-api-bogota-ventas.webp',
    gradient: 'from-indigo-500 to-violet-500',
  },
];
