export const projects = [
  {
    title: 'Yoica.com',
    desc: 'Plataforma de productos naturales enfocada en bienestar con diseño limpio y conversión optimizada.',
    category: 'E-commerce',
    tags: ['WordPress', 'WooCommerce', 'SEO'],
    link: 'https://yoica.com',
    image: '/images/yoica.png',
    gradient: 'from-emerald-500 to-teal-500',
  },
  {
    title: 'SembrandoConfianza.com',
    desc: 'Agricultura sostenible con enfoque comunitario. Migración completa y optimización SEO local.',
    category: 'Desarrollo Web',
    tags: ['WordPress', 'SEO', 'Migración'],
    link: 'https://sembrandoconfianza.com/',
    image: '/images/sembrando.png',
    gradient: 'from-green-500 to-lime-500',
  },
  {
    title: 'ConoceTusDerechos.co',
    desc: 'Plataforma informativa para asesoría jurídica con foco en accesibilidad y experiencia de usuario.',
    category: 'Informativo',
    tags: ['UX/UI', 'Accesibilidad', 'WordPress'],
    link: 'https://conocetusderechos.co/',
    image: '/images/conoce.png',
    gradient: 'from-blue-500 to-indigo-500',
  },
  {
    title: 'TiendaDelChocolate.com',
    desc: 'E-commerce premium para chocolates artesanales con integración WooCommerce y diseño de marca.',
    category: 'E-commerce',
    tags: ['WooCommerce', 'Branding', 'Premium'],
    link: 'https://tiendadelchocolate.com/',
    image: '/images/chocolate.png',
    gradient: 'from-amber-600 to-orange-600',
  },
  {
    title: 'Ananassa.co',
    desc: 'E-commerce de fresas con chocolate. SEO GEO, analítica, UX moderno y automatización.',
    category: 'E-commerce',
    tags: ['E-commerce', 'SEO GEO', 'IA'],
    link: 'https://ananassa.co/',
    image: '/images/ananassa.png',
    gradient: 'from-pink-500 to-rose-500',
  },
  {
    title: 'WooCar.io',
    desc: 'Aplicación web para alquiler de vehículos eléctricos, conectada a API y backend personalizado.',
    category: 'App Web',
    tags: ['React', 'API', 'Backend'],
    link: 'https://woocar.io/',
    image: '/images/woocar.png',
    gradient: 'from-cyan-500 to-blue-500',
  },
  {
    title: 'Florida2R.com',
    desc: 'Sitio inmobiliario con filtros avanzados y fichas dinámicas integradas con CRM.',
    category: 'Inmobiliario',
    tags: ['CRM', 'Filtros', 'WordPress'],
    link: 'http://florida2r.com/',
    image: '/images/florida.png',
    gradient: 'from-violet-500 to-purple-500',
  },
  {
    title: 'Cristian.click',
    desc: 'Portfolio personal optimizado con animaciones React y estructura escalable para SEO técnico.',
    category: 'Portfolio',
    tags: ['React', 'SEO', 'Animaciones'],
    link: 'https://cristian.click',
    image: '/images/portafolio.png',
    gradient: 'from-slate-500 to-gray-600',
  },
  {
    title: 'KLDiseñoYConstrucción.com',
    desc: 'Sitio corporativo de arquitectura con enfoque en estética, velocidad y SEO.',
    category: 'Corporativo',
    tags: ['Corporativo', 'SEO', 'Diseño'],
    link: 'https://kldisenoyconstruccion.com/',
    image: '/images/kldiseno.png',
    gradient: 'from-orange-500 to-red-500',
  },
  {
    title: 'BicicletasElectricasBogota.com.co',
    desc: 'Tienda de movilidad eléctrica con UX enfocado en conversiones y productos dinámicos.',
    category: 'E-commerce',
    tags: ['E-commerce', 'SEO GEO', 'Conversión'],
    link: 'https://bicicletaselectricasbogota.com.co/',
    image: '/images/bicicletas.png',
    gradient: 'from-green-500 to-emerald-500',
  },
  {
    title: 'ImperialDunas.com',
    desc: 'Resort de lujo frente al mar con diseño premium, integración de reservas y optimización global.',
    category: 'Hospitality',
    tags: ['Premium', 'Reservas', 'Performance'],
    link: 'https://imperialdunas.com/',
    image: '/images/imperial.png',
    gradient: 'from-blue-600 to-cyan-600',
  },
  {
    title: 'Hoffman-Latam.com',
    desc: 'Mantenimiento técnico y optimización de rendimiento para empresa de fotografía profesional.',
    category: 'Mantenimiento',
    tags: ['Mantenimiento', 'Performance', 'Fotografía'],
    link: 'https://hoffman-latam.com/',
    image: '/images/hoffman.png',
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    title: 'Chatbot WhatsApp con IA',
    desc: 'Bot de WhatsApp con IA para automatizar atención y ventas sobre WhatsApp Business API.',
    category: 'Automatización',
    tags: ['WhatsApp API', 'IA', 'Automatización'],
    link: 'https://github.com/Crnustes/api_whatsapp_techtecnic',
    image: '/images/chatbot-whatsapp-business-api-bogota-ventas.webp',
    gradient: 'from-indigo-500 to-violet-500',
  },
];
